language: python
python:
- '3.6'
install:
- pip install social-auth-app-django
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: "cdd34d91-cffa-4d22-9156-3575f3a8c078"
  on:
    repo: uva-cs3240-f19/project-103-letsgitit
    branch: master
