language: python
python:
- '3.6'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: gCm5vzN7qNyfs-ixWqq6jg
  app: Rideshare_app
  on:
    repo: uva-cs3240-f19/project-103-letsgitit
    branch: master
