# Generated by Django 2.2.5 on 2019-10-24 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rideshare_app', '0004_auto_20191012_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='ride',
        ),
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Rideshare_app.Driver'),
        ),
        migrations.AddField(
            model_name='ride',
            name='riders',
            field=models.ManyToManyField(to='Rideshare_app.Rider'),
        ),
    ]
