# Generated by Django 2.2.5 on 2019-11-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rideshare_app', '0005_auto_20191024_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='departure_state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='destination_state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='riders',
            field=models.ManyToManyField(blank=True, to='Rideshare_app.Rider'),
        ),
    ]
