# Generated by Django 2.2.5 on 2019-11-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rideshare_app', '0006_auto_20191108_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='car_make',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='car_model',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='venmo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='confirmed_riders',
            field=models.ManyToManyField(blank=True, related_name='confirmed_riders', to='Rideshare_app.Rider'),
        ),
        migrations.AddField(
            model_name='ride',
            name='pending_riders',
            field=models.ManyToManyField(blank=True, related_name='pending_riders', to='Rideshare_app.Rider'),
        ),
        migrations.AddField(
            model_name='ride',
            name='seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
