# Generated by Django 2.2.5 on 2019-11-09 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rideshare_app', '0008_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='car_make',
        ),
        migrations.RemoveField(
            model_name='user',
            name='car_model',
        ),
        migrations.AddField(
            model_name='user',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Rideshare_app.Driver'),
        ),
        migrations.AddField(
            model_name='user',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Rideshare_app.Rider'),
        ),
    ]
