# Generated by Django 2.2.5 on 2019-11-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rideshare_app', '0009_auto_20191109_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='venmo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
