# Generated by Django 2.2.5 on 2019-11-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rideshare_app', '0010_ride_price'),
        ('Rideshare_app', '0010_rider_venmo'),
    ]

    operations = [
    ]
