# Generated by Django 2.2.5 on 2019-11-11 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rideshare_app', '0010_rider_venmo'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='pending_rides',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_rides', to='Rideshare_app.Ride'),
        ),
    ]
