# Generated by Django 2.2.5 on 2019-11-11 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rideshare_app', '0011_merge_20191111_1552'),
        ('Rideshare_app', '0011_merge_20191111_1513'),
    ]

    operations = [
    ]
