# Generated by Django 2.2.5 on 2019-11-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rideshare_app', '0011_driver_pending_rides'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='pending_rides',
        ),
        migrations.AddField(
            model_name='driver',
            name='pending_rides',
            field=models.ManyToManyField(blank=True, null=True, related_name='confirmed_rides', to='Rideshare_app.Ride'),
        ),
    ]
