# Generated by Django 2.2.5 on 2019-11-17 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rideshare_app', '0012_merge_20191111_1714'),
        ('Rideshare_app', '0011_merge_20191117_1803'),
    ]

    operations = [
    ]
