# Generated by Django 2.2.5 on 2019-11-18 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rideshare_app', '0013_merge_20191117_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ride',
            name='seats',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
